In [15]:
import numpy as np
arr=np.random.randint(1,10,size=(5,10))
b=arr.reshape(2,25)
print(arr)
print("b=",b)
print("\n")
#Flattening or convert into 1D array:

c=np.ravel(arr,order='F')         #ordering according to row
print("C=",c)
print(" \n")
d=np.ravel(arr,order='c')         #ordering according to row
print("D=",d)

[[6 3 5 1 3 8 1 1 7 2]
 [4 4 6 8 9 7 6 1 1 3]
 [6 2 7 9 7 5 6 1 7 9]
 [6 9 3 3 3 3 3 4 7 8]
 [1 8 6 6 7 1 1 9 1 5]]
b= [[6 3 5 1 3 8 1 1 7 2 4 4 6 8 9 7 6 1 1 3 6 2 7 9 7]
 [5 6 1 7 9 6 9 3 3 3 3 3 4 7 8 1 8 6 6 7 1 1 9 1 5]]


C= [6 4 6 6 1 3 4 2 9 8 5 6 7 3 6 1 8 9 3 6 3 9 7 3 7 8 7 5 3 1 1 6 6 3 1 1 1
 1 4 9 7 1 7 7 1 2 3 9 8 5]
 

D= [6 3 5 1 3 8 1 1 7 2 4 4 6 8 9 7 6 1 1 3 6 2 7 9 7 5 6 1 7 9 6 9 3 3 3 3 3
 4 7 8 1 8 6 6 7 1 1 9 1 5]


In [27]:
#Concatenet:
a=np.random.randint(1,5,size=(2,3))
b=np.random.randint(1,5,size=(2,3))
print("a=",a,"\n","\n","b=",b,"\n")

row=np.concatenate((a,b),axis=0) #for row concatenate col should be same in deimension of those matrix
print(row,"\n")
row=np.concatenate((a,b),axis=1) #for col concatenate row should be same in deimension of those matrix
print(row,"\n")

a= [[4 4 1]
 [2 4 2]] 
 
 b= [[2 3 3]
 [4 3 3]] 

[[4 4 1]
 [2 4 2]
 [2 3 3]
 [4 3 3]] 

[[4 4 1 2 3 3]
 [2 4 2 4 3 3]] 



In [41]:
#Transpose matrix:
a=np.random.randint(1,5,size=(2,3))
mat=a.T
print(mat,"\n")


#array_split and split: 
arr=np.random.randint(1,10,size=(10,))     #when data equally division isn't possible
b=np.array_split(arr,3)
print("b=",b,"\n")

arr1=np.random.randint(1,10,size=(9,))     #when data equally division possible
c=np.split(arr1,3)
print("c=",c)


[[4 2]
 [1 3]
 [3 4]] 

b= [array([7, 3, 2, 6]), array([6, 7, 5]), array([4, 9, 4])] 

c= [array([1, 7, 8]), array([8, 9, 2]), array([7, 3, 1])]


In [92]:
#vectorization is faster in array:
a=np.random.randint(1,5,size=(2,3))
b=np.random.randint(1,5,size=(2,3))
print(a,"\n",b,"\n")
add=a+b
print(add)
  #same as:
sub=a-b
mul=a*b
div=a/b
print("mul=",mul,"\n")
#Trigonometric: sin, cos, ... values in rediant
sine=np.sin(a)
print(sine)

  #degree to rediant and vice versa:
rad=np.deg2rad(a)
print(rad)  #same for rad2deg

#log: how many times a division is possible by the base of log
log=np.log10(a)
log1=np.log2(b)
sqrt=np.sqrt(a)
total_sum=sum(a)
cummulative_sum=np.cumsum(a)

[[3 4 1]
 [4 1 1]] 
 [[4 2 3]
 [2 4 2]
 [1 2 2]] 



ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [55]:
#Logical operator:>,<,==,..
a=np.random.randint(1,5,size=(2,3))
b=np.random.randint(1,5,size=(2,3))
greater=a>b
print(greater)

#To check true and false after complete a operation: all(), any()
check1=np.all(greater)
print(check1)
check2=np.any(greater)
print(check2)

[[False  True False]
 [ True False False]]
False
True


In [76]:
#Sorting 

x = np.array([2, 4, 1, 9, 4])

z = x.copy()
print(z)

z.sort()   #Inplace Sorting
print(z)
print(x)
print("\n")

a=np.array([5,3,4,7,1])
y=np.sort(a)  #copy sorting
print(y)

arr2 =np.array([[1,4,3,2,5],
                [6,9,8,7,10]])
row_sort=np.sort(arr2,axis=1)
print(row_sort)

[2 4 1 9 4]
[1 2 4 4 9]
[2 4 1 9 4]


[1 3 4 5 7]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [87]:
#Searching:
arr2 =np.array([[1,4,3,2,5],
                [6,9,8,7,10]])
index=np.where(x>arr2)           #finding array position/index
value=np.where(x>arr2,x,10)      #cand modify the array
print(index)
print(value)

max=np.argmax(arr2)  #finding max value's index
min=np.argmin(arr2)  #finding max value's index
print(max)
print(min)

#Count:
count=np.count_nonzero(arr2>10)
print(count)
unique=np.unique(arr2,return_counts=True)
print(unique)

(array([0, 0, 1]), array([0, 3, 3]))
[[ 2 10 10  9 10]
 [10 10 10  9 10]]
9
0
0
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))


In [90]:
#correlation:
a=np.random.randint(1,5,size=(2,3))
b=np.random.randint(1,5,size=(2,3))
print("a=",a,"\n","\n","b=",b,"\n")

row=np.concatenate((a,b),axis=0) #for row concatenate col should be same in deimension of those matrix

row=np.concatenate((a,b),axis=1) #for col concatenate row should be same in deimension of those matrix

correltn=np.corrcoef(row)
print(correltn)

a= [[1 1 1]
 [2 1 2]] 
 
 b= [[1 1 3]
 [2 2 2]] 

[[1.  0.2]
 [0.2 1. ]]


In [ ]:
#Linear Algebra:
#np.dot(x,y); np.trace(x); determinant=np.linalg.det(x); np.matrix_rank(x)